main: ca.bungo.lc.core.LootableCorpses
name: ${project.name}
version: ${project.version}
author: Nick Barudi
description: ${project.description}
website: ${project.url}
depend: [ProtocolLib]
api-version: 1.13
commands:
  test:
    description: Testing Command
    permission: lc.op
    usage: /test